### ISSUE TITLE
R-LKDepth shared parameters for feature extraction using resnet-18

### ISSUE THREAD

**Issue by luck-grz** [jsczzzk/R-LKDepth#1]
Hello, can you share the parameters of the R-LKDepth model using resnet-18 for deep feature extraction and R-MSFM? The R-LKDepth using resnet-18 for feature extraction is very helpful for my research direction, thank you for sharing.

**Comment by jsczzzk** [comment]
![image](https://github.com/user-attachments/assets/c676df60-a282-40c5-8080-43d16d4f0fbf)
You can refer to Table III in the original paper.

**Comment by luck-grz** [comment]
> ![图像](https://private-user-images.githubusercontent.com/32475718/398821884-c676df60-a282-40c5-8080-43d16d4f0fbf.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzUyNjg1MTksIm5iZiI6MTczNTI2ODIxOSwicGF0aCI6Ii8zMjQ3NTcxOC8zOTg4MjE4ODQtYzY3NmRmNjAtYTI4Mi00MGM1LTgwODAtNDNkMTZkNGYwZmJmLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDEyMjclMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQxMjI3VDAyNTY1OVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTQ3MjdiN2YxODkyOTY0MTM0NjFmZGYzMzE3NmEwYmY2MGVjMmQ2NTgzMmE5N2QwNTc2ODU2YzhiMzZkY2FiODcmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0.xM6qjYnf5ZhshtQCzW6IDP7FluWD7hseuE_vSg91rpA)您可以参考原始论文中的表 III。

Thanks, I tried to revise it according to this one of the paper, and when I ran out to see the results
