### ISSUE TITLE
Why is the R-LKDepth I ran with resnet-18 feature extraction not as good as R-MSFM?

### ISSUE THREAD

**Issue by luck-grz** [jsczzzk/R-LKDepth#2]
I used resnet-18 for feature extraction and adjusted the parameters of the R-LKDepth model, but the performance was not as good as the R-MSFM model with resnet-18 for feature extraction. I hope you can share the parameters you measured.

**Comment by jsczzzk** [comment]
You can refer to Table III in the original paper.
![image](https://github.com/user-attachments/assets/40c8582d-0537-4bc8-a9b8-93b4c9c8f170)
